package com.obelus.domain.usecase

import android.content.Context
import android.os.Environment
import com.itextpdf.kernel.colors.DeviceRgb
import com.itextpdf.kernel.font.PdfFontFactory
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.borders.SolidBorder
import com.itextpdf.layout.element.Cell
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.element.Table
import com.itextpdf.layout.properties.TextAlignment
import com.itextpdf.layout.properties.VerticalAlignment
import com.obelus.domain.model.VehicleHealthSummary
import java.io.File
import java.text.SimpleDateFormat
import java.util.*
import javax.inject.Inject

class GenerateHealthPdfReportUseCase @Inject constructor() {

    private val neonCyan = DeviceRgb(0, 212, 170)
    private val darkBackground = DeviceRgb(10, 10, 15)
    private val textColor = DeviceRgb(224, 224, 224)

    fun execute(context: Context, summary: VehicleHealthSummary): File {
        val fileName = "Vehicle_Health_Report_${summary.fingerprint.vin}_${System.currentTimeMillis()}.pdf"
        val file = File(context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS), fileName)
        
        val writer = PdfWriter(file)
        val pdf = PdfDocument(writer)
        val document = Document(pdf)
        
        // Load fonts
        val boldFont = PdfFontFactory.createFont(com.itextpdf.io.font.constants.StandardFonts.HELVETICA_BOLD)
        val monoFont = PdfFontFactory.createFont(com.itextpdf.io.font.constants.StandardFonts.COURIER)

        // Header
        document.add(Paragraph("OBELUS PROFESSIONAL VEHICLE HEALTH REPORT")
            .setFontSize(20f)
            .setFont(boldFont)
            .setTextAlignment(TextAlignment.CENTER)
            .setFontColor(neonCyan))

        document.add(Paragraph("Generated on: ${SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US).format(Date())}")
            .setTextAlignment(TextAlignment.RIGHT)
            .setFontSize(10f))

        document.add(Paragraph("\n"))

        // 2. FICHA TÉCNICA DEL VEHÍCULO (Identity Section)
        document.add(Paragraph("FICHA TÉCNICA DEL VEHÍCULO")
            .setBold()
            .setFontSize(14f)
            .setFontColor(neonCyan))

        val identityTable = Table(floatArrayOf(1f, 2f)).useAllAvailableWidth()
        
        addIdentityRow(identityTable, "VIN", summary.fingerprint.vin, monoFont)
        addIdentityRow(identityTable, "HW REF", summary.fingerprint.hwRef, monoFont)
        addIdentityRow(identityTable, "SW VERSION", summary.fingerprint.swVersion, monoFont)
        addIdentityRow(identityTable, "CALIBRATION ID", summary.fingerprint.calId, monoFont)
        addIdentityRow(identityTable, "BATTERY VOLTAGE", "${String.format(Locale.US, "%.2f", summary.batteryVoltage)} V", monoFont)

        document.add(identityTable)

        document.add(Paragraph("\nSYSTEM SCAN RESULTS").setBold().setFontSize(14f))
        
        val scanTable = Table(floatArrayOf(3f, 2f, 4f)).useAllAvailableWidth()
        scanTable.addHeaderCell(createHeaderCell("Module Name"))
        scanTable.addHeaderCell(createHeaderCell("Status"))
        scanTable.addHeaderCell(createHeaderCell("DTCs Found"))

        summary.ecusFound.forEach { ecu ->
            val dtcs = summary.dtcsByEcu[ecu.name] ?: emptyList()
            scanTable.addCell(createDataCell(ecu.name))
            
            if (dtcs.isEmpty()) {
                scanTable.addCell(createDataCell("HEALTHY", DeviceRgb(0, 255, 102)))
                scanTable.addCell(createDataCell("No errors detected."))
            } else {
                scanTable.addCell(createDataCell("ERROR", DeviceRgb(255, 68, 68)))
                scanTable.addCell(createDataCell(dtcs.joinToString(", ")))
            }
        }
        
        document.add(scanTable)
        
        document.add(Paragraph("\n\nDisclaimer: This report is generated by Obelus Diagnostic Engine. Codes are for professional reference.")
            .setFontSize(8f)
            .setItalic()
            .setTextAlignment(TextAlignment.CENTER))

        document.close()
        return file
    }

    private fun addIdentityRow(table: Table, label: String, value: String, monoFont: com.itextpdf.kernel.font.PdfFont) {
        val labelCell = Cell().add(Paragraph(label).setBold())
            .setBackgroundColor(darkBackground)
            .setFontColor(neonCyan)
            .setBorder(SolidBorder(neonCyan, 1f))
            .setPadding(5f)
        
        val valStr = if (value.isBlank() || value == "NO DATA") "NO DATA" else value
        val valColor = if (valStr == "NO DATA") DeviceRgb(120, 120, 120) else textColor
        
        val valueCell = Cell().add(Paragraph(valStr).setFont(monoFont))
            .setBackgroundColor(darkBackground)
            .setFontColor(valColor)
            .setBorder(SolidBorder(neonCyan, 1f))
            .setPadding(5f)
            
        table.addCell(labelCell)
        table.addCell(valueCell)
    }

    private fun createHeaderCell(text: String): Cell {
        return Cell().add(Paragraph(text).setBold())
            .setBackgroundColor(DeviceRgb(30, 30, 40))
            .setFontColor(neonCyan)
            .setTextAlignment(TextAlignment.CENTER)
            .setPadding(5f)
    }

    private fun createDataCell(text: String, color: DeviceRgb = textColor): Cell {
        return Cell().add(Paragraph(text))
            .setFontColor(color)
            .setVerticalAlignment(VerticalAlignment.MIDDLE)
            .setPadding(5f)
    }
}
